name: CI

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-clement.lagasse.git

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check good files & folders
        run: |
          paths=($(find . -name '#*#' -o -name '*-' -o -name '*.tmp' -o -name '*.o' -o -name '*.a' -o -name '*.so' -o -name '*.gcno' -o -name '*.gcda' -o -name '*.gcov' -o -type d -name 'tmp'))
          if [[ ! -z "$path" ]]; then
            IFS=$'\n'
            for FILE in "${paths[@]}"; do echo "::error title=Unwanted file detected,file=$FILE::$FILE"; done
            unset IFS
            exit 1
          fi

  check_program_compilation_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile Program
        run: |
          mkdir build
          cd build
          cmake ..
          make

  validate_pull_request:
    needs: check_repository_cleanliness
    runs-on: ubuntu-latest
    steps:
      - name: Wait for review
        id: review
        uses: actions/github/wait-for-review@v1
        with:
          permissions: read
          reviewers: "HarryTheoBartAlexClemDev/Reviewers"
      - name: Check if review was approved
        run: |
          if [ "${{ steps.review.outputs.approved }}" != "true" ]; then
            echo "PR review not approved by any organization member. Exiting workflow."
            exit 1
          fi

  push_to_mirror:
    needs: check_program_compilation_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
