name: Push to mirror

on:
  pull_request:
    types: [review_requested]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-clement.lagasse.git

concurrency:
  group: push_to_mirror

jobs:
  validate_pull_request:
    name: Validate pull request
    runs-on: ubuntu-latest
    steps:
      - name: Check if review was approved
        run: |
          if [ "${{ steps.review.outputs.approved }}" != "true" ]; then
            echo "PR review not approved by any organization member. Exiting workflow."
            exit 1
          fi

  push_to_mirror:
    needs: validate_pull_request
    name: Push to mirror repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_MIRROR_KEY }}
