name: Mirror Repository

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-clement.lagasse.git

on:
  push:
    paths-ignore:
      - ".github/workflows/**" # Exclude the workflows

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository
        uses: wearerequired/git-mirror-action@v1
        with:
          source-repository: ${{ github.repository }}
          destination-repository: ${{ env.MIRROR_URL }}
          ssh-private-key: ${{ secrets.MIRROR_SSH_KEY }}
          source-github-token: ${{ secrets.PERSONAL_TOKEN }}
