name: Mirror Repository

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-clement.lagasse.git

on:
  push:
    paths-ignore:
      - ".github/**" # Exclude the workflows
  delete:
  create:

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_MIRROR_KEY }}
        with:
          source-repo: "git@github.com:HarryTheoBartAlexClemDev/RType.git"
          destination-repo: "git@github.com:EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-clement.lagasse.git"
